[package]
name = "rust_deno_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
deno_core = "0.214.0"
serde = "1.0.188"
tokio = "1.32.0"
